Name:           lemonade
Version:        10.0.1
Release:        4
Summary:        Lightweight, high-performance local LLM server
License:        Apache-2.0
URL:            https://lemonade-server.ai/
# Upstream source is vendored via the lemonade/ git submodule (pinned at v%%{version}).
# The tarball is generated by tito's SubmoduleAwareBuilder and submitted to COPR as an SRPM.
Source0:        %{name}-%{version}.tar.gz
%global upstream lemonade

%define debug_package %{nil}

# C++ build toolchain (server + tray)
BuildRequires:  cmake
BuildRequires:  ninja-build
BuildRequires:  gcc-c++
BuildRequires:  git

# lemonade-server
BuildRequires:  systemd-rpm-macros
BuildRequires:  systemd-devel
BuildRequires:  libcurl-devel
BuildRequires:  libzstd-devel
BuildRequires:  libwebsockets-devel
BuildRequires:  libdrm-devel
BuildRequires:  nlohmann-json-devel >= 3.11.3
BuildRequires:  cli11-devel >= 2.4.2
BuildRequires:  cpp-httplib-devel >= 0.26.0

# lemonade-tray
BuildRequires:  gtk3-devel
BuildRequires:  libappindicator-gtk3-devel
BuildRequires:  libnotify-devel

# lemonade-app
BuildRequires:  nodejs
BuildRequires:  npm

# packaging validation
BuildRequires:  desktop-file-utils
BuildRequires:  libappstream-glib

Requires:       %{name}-server = %{version}-%{release}
Requires:       %{name}-app = %{version}-%{release}

%description
Lemonade is a lightweight, high-performance local LLM server with support for
multiple backends including llama.cpp, FastFlowLM, and RyzenAI.

This package is a meta-package that installs both the Lemonade server and the
desktop application.

%package server
Summary:        Server components for Lemonade
Provides:       lemonade-cli = %{version}-%{release}
Provides:       lemonade-router = %{version}-%{release}
Provides:       lemonade-web = %{version}-%{release}
# Required to create the lemonade system user in %pre
Requires(pre):  shadow-utils
%{?systemd_requires}
# lemonade-web falls back to xdg-open when no Chromium browser is found
Requires:       xdg-utils
# owns /usr/share/icons/hicolor/ tree where the app icon is installed
Requires:       hicolor-icon-theme

%description server
The Lemonade server subpackage contains the core LLM server and web interface.

%package tray
Summary:        System tray application for Lemonade
Requires:       %{name}-server%{?_isa} = %{version}-%{release}
%{?systemd_user_requires}

%description tray
Provides the lemonade-tray GUI application and a user systemd service for
running the Lemonade server in the system tray during graphical sessions.

%package app
Summary:        Desktop application for Lemonade
Requires:       %{name}-server%{?_isa} = %{version}-%{release}
# Fedora usually bundles Electron or uses a system-wide one;
# this spec assumes an Electron-based build.
Requires:       electron

%description app
A modern desktop interface for managing and interacting with the
Lemonade LLM server.

%prep
%autosetup -n %{name}-%{version}
# All upstream source lives in the %{upstream} subdirectory (git submodule)
pushd %{upstream}
# Fix httplib detection and linking on Fedora (where it is header-only and has no .pc file)
sed -i 's/set(USE_SYSTEM_HTTPLIB ${HTTPLIB_FOUND})/set(USE_SYSTEM_HTTPLIB ${HTTPLIB_INCLUDE_DIRS})/' CMakeLists.txt
find . -name 'CMakeLists.txt' -exec sed -i 's/PRIVATE cpp-httplib/PRIVATE httplib::httplib/g' {} +
# Ensure httplib::httplib target is defined via find_package
sed -i '/include(GNUInstallDirs)/a find_package(httplib REQUIRED)' CMakeLists.txt
# FetchContent is always needed on Linux, even when all other deps are system packages
sed -i '/include(GNUInstallDirs)/a include(FetchContent)' CMakeLists.txt
# System service runs headless; tray is for user sessions only
sed -i 's|lemonade-server serve$|lemonade-server serve --no-tray|' data/lemonade-server.service.in
popd

%build
# Configure from within the upstream source subdirectory (%{upstream}/)
pushd %{upstream}
%cmake -G Ninja \
    -DBUILD_WEB_APP=OFF \
    -DBUILD_ELECTRON_APP=OFF \
    -DUSE_SYSTEM_JSON=ON \
    -DUSE_SYSTEM_CLI11=ON \
    -DUSE_SYSTEM_HTTPLIB=ON \
    -DREQUIRE_LINUX_TRAY=ON
%cmake_build
popd

# Build the Electron app
# Note: Fedora builds are offline. In a production Koji/Mock build,
# you would provide a pre-bundled node_modules tarball and use --offline.
pushd %{upstream}/src/app
npm config set audit false
npm install
npm run build:linux
popd

%install
pushd %{upstream}
%cmake_install
popd

# --- Icons ---
# Install the application icon into the hicolor theme.
# Named "lemonade" so it is referenced consistently by the desktop entries
# and resolved automatically by the system tray (AppIndicator3/SNI).
install -Dpm 0644 %{upstream}/src/app/assets/logo.svg \
    %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/lemonade.svg

# --- Web app launcher ---
# Shell script that opens the built-in web interface in the user's browser.
install -Dpm 0755 %{upstream}/data/lemonade-web-app \
    %{buildroot}%{_bindir}/lemonade-web

# --- Desktop entries ---
# lemonade.desktop: Electron desktop app (app subpackage)
desktop-file-install \
    --dir=%{buildroot}%{_datadir}/applications \
    --set-icon=lemonade \
    %{upstream}/data/lemonade-app.desktop
mv %{buildroot}%{_datadir}/applications/lemonade-app.desktop \
   %{buildroot}%{_datadir}/applications/lemonade.desktop

# lemonade-web.desktop: web interface launcher (base package)
desktop-file-install \
    --dir=%{buildroot}%{_datadir}/applications \
    --set-key=Exec --set-value=lemonade-web \
    --set-icon=lemonade \
    %{upstream}/data/lemonade-web-app.desktop
mv %{buildroot}%{_datadir}/applications/lemonade-web-app.desktop \
   %{buildroot}%{_datadir}/applications/lemonade-web.desktop

# --- AppStream metadata ---
install -Dpm 0644 /dev/stdin \
    %{buildroot}%{_datadir}/metainfo/lemonade.appdata.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>lemonade</id>
  <metadata_license>FSFAP</metadata_license>
  <project_license>Apache-2.0</project_license>
  <name>Lemonade</name>
  <summary>Lightweight, high-performance local LLM server</summary>
  <description>
    <p>
      Lemonade is a lightweight, high-performance local LLM server with support for
      multiple backends including llama.cpp, FastFlowLM, and RyzenAI.
    </p>
  </description>
  <launchable type="desktop-id">lemonade.desktop</launchable>
  <launchable type="desktop-id">lemonade-web.desktop</launchable>
  <url type="homepage">https://lemonade-server.ai/</url>
  <provides>
    <binary>lemonade-server</binary>
    <binary>lemonade-web</binary>
    <binary>lemonade-app</binary>
  </provides>
</component>
EOF

# --- Electron app ---
# electron-builder names the binary after productName (lowercased) = "lemonade"
mkdir -p %{buildroot}%{_libdir}/lemonade-app
cp -r %{upstream}/src/app/dist-app/linux-unpacked/* %{buildroot}%{_libdir}/lemonade-app/

# Wrapper script so lemonade-app is findable in PATH (required by lemonade.desktop Exec=lemonade-app)
install -Dpm 0755 /dev/stdin \
    %{buildroot}%{_bindir}/lemonade-app << 'EOF'
#!/bin/sh
exec %{_libdir}/lemonade-app/lemonade "$@"
EOF

# --- User systemd unit (tray) ---
# Runs lemonade-tray for graphical user sessions.
# Users can enable it with: systemctl --user enable --now lemonade-tray.service
install -Dpm 0644 /dev/stdin \
    %{buildroot}%{_userunitdir}/lemonade-tray.service << 'EOF'
[Unit]
Description=Lemonade Server (System Tray)
Documentation=https://lemonade-server.ai/
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=%{_bindir}/lemonade-tray
Restart=on-failure
RestartSec=5s
KillSignal=SIGINT

[Install]
WantedBy=graphical-session.target
EOF

# --- System user home directory ---
# /var/lib/lemonade is WorkingDirectory and ReadWritePaths for the service unit.
install -dm 0750 %{buildroot}%{_sharedstatedir}/lemonade

%pre server
# Create the lemonade system group and user if they do not already exist.
getent group lemonade >/dev/null || groupadd -r lemonade
getent passwd lemonade >/dev/null || \
    useradd -r -g lemonade -d %{_sharedstatedir}/lemonade \
            -s /sbin/nologin -c "Lemonade Server" lemonade

%post server
%systemd_post lemonade-server.service
# Set ownership of the working directory now that the lemonade user exists.
chown lemonade:lemonade %{_sharedstatedir}/lemonade
chmod 0750 %{_sharedstatedir}/lemonade

%preun server
%systemd_preun lemonade-server.service

%postun server
%systemd_postun_with_restart lemonade-server.service

%post tray
%systemd_user_post lemonade-tray.service

%preun tray
%systemd_user_preun lemonade-tray.service

%postun tray
%systemd_user_postun_with_restart lemonade-tray.service

%check
appstream-util validate-relax --nonet %{buildroot}%{_datadir}/metainfo/lemonade.appdata.xml
desktop-file-validate %{buildroot}%{_datadir}/applications/lemonade.desktop
desktop-file-validate %{buildroot}%{_datadir}/applications/lemonade-web.desktop

%files

%files server
%license LICENSE
%doc README.md
%{_bindir}/lemonade
%{_bindir}/lemonade-router
%{_bindir}/lemonade-server
%{_bindir}/lemonade-web
%{_mandir}/man1/lemonade.1*
%{_mandir}/man1/lemonade-router.1*
%{_mandir}/man1/lemonade-server.1*
%{_datadir}/lemonade-server/
%{_datadir}/icons/hicolor/scalable/apps/lemonade.svg
%{_datadir}/applications/lemonade-web.desktop
%dir %{_sysconfdir}/lemonade
%config(noreplace) %{_sysconfdir}/lemonade/lemonade.conf
%dir %{_sysconfdir}/lemonade/conf.d
%config(noreplace) %{_sysconfdir}/lemonade/conf.d/zz-secrets.conf
%{_unitdir}/lemonade-server.service
%dir %{_sharedstatedir}/lemonade

%files tray
%{_bindir}/lemonade-tray
%{_userunitdir}/lemonade-tray.service

%files app
%{_bindir}/lemonade-app
%{_libdir}/lemonade-app/
%{_datadir}/applications/lemonade.desktop
%{_datadir}/metainfo/lemonade.appdata.xml

%changelog
* Mon Mar 30 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 10.0.1-4
- fix: cmake_install must run from within upstream source directory
  (arun.neelicattu@gmail.com)

* Mon Mar 30 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 10.0.1-3
- fix: vendor upstream source via submodule for COPR compatibility
  (arun.neelicattu@gmail.com)

* Mon Mar 30 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 10.0.1-2
- fix(tito): use correct builder (arun.neelicattu@gmail.com)
- fix: lemonade-tray.service should use lemonade-tray binary
  (arun.neelicattu@gmail.com)
- docs: document lemonade-tray as a standalone install option
  (arun.neelicattu@gmail.com)

* Mon Mar 30 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 10.0.1-1
- spec: update to 10.0.1 (arun.neelicattu@gmail.com)
- Automatic commit of package [lemonade] minor release [9.4.1-2].
  (arun.neelicattu@gmail.com)

* Sun Mar 01 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 9.4.1-2
- 

* Sun Mar 01 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 9.4.1-1
- update lemonade submodule to v9.4.1 (arun.neelicattu@gmail.com)

* Fri Feb 27 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 9.3.4-6
- fix: tray systemd unit cannot depend on lemonade-server
  (arun.neelicattu@gmail.com)

* Fri Feb 27 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 9.3.4-5
- spec: fix autosetup after rename (arun.neelicattu@gmail.com)

* Fri Feb 27 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 9.3.4-4
- spec: fix incorrect source after rename (arun.neelicattu@gmail.com)

* Fri Feb 27 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 9.3.4-3
- tito: update tagger (arun.neelicattu@gmail.com)

* Fri Feb 27 2026 Arun Babu Neelicattu <arun.neelicattu@gmail.com> 9.3.4-2
- new package built with tito

* Thu Feb 26 2026 Arun Neelicattu <arun.neelicattu@gmail.com> - 9.3.4-1
Initial package source
